//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGui.AccountValidation {
    using System.Data;
    using System.Net;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.tpvaoc.com/accws", ConfigurationName="AccountValidation.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/LoademailByAD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoademailByAD(string domain, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/LoademailByAD2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoademailByAD2(string domain, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/CheckAD_Multiserver", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckAD_Multiserver(string domain, string username, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/CheckAD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckAD(string domain, string username, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/CheckAD_old", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckAD_old(string domain, string username, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/CheckSysUserLoginV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckSysUserLoginV2(string SystemID, string SafeCode, string UserID, string EncodedUserPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/CheckSysUserLogin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckSysUserLogin(string SystemID, string SafeCode, string UserID, string UserPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/CheckUserAction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckUserAction(string SystemID, string SafeCode, string UserID, string ActionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/CheckUserActionSimply", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckUserActionSimply(string SystemID, string SafeCode, string UserID, string ActionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/GetUserSystem01", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUserSystem01(string SystemID, string SafeCode, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/GetUserGroup01", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUserGroup01(string SystemID, string SafeCode, string ActGrpID, string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/ChangeUserPwd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChangeUserPwd(string SystemID, string SafeCode, string UserID, string OldPwd, string NewPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/ChangeUserGlobalPwd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ChangeUserGlobalPwd(string UserID, string OldPwd, string NewPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/GetUserInfoByUserID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserInfoByUserID(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/GetUserDetailByUserID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserDetailByUserID(string UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/GetUserInfoByUserAD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserInfoByUserAD(string UserAD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/GetUserDetailByUserAD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetUserDetailByUserAD(string UserAD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/GetSysUserByRoleID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetSysUserByRoleID(string SystemID, string SafeCode, string RoleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/CheckUserGlobalPwd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckUserGlobalPwd(string UserID, string UserPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/GetServerIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetServerIP();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/GetLeaveEmp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLeaveEmp(string SiteCode, string CreateDate_s, string CreateDate_e);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.tpvaoc.com/accws/GeUserDomain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool GeUserDomain(string userAD);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : WebGui.AccountValidation.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<WebGui.AccountValidation.ServiceSoap>, WebGui.AccountValidation.ServiceSoap {
        
        public ServiceSoapClient() {
            ServicePointManager.SecurityProtocol = (SecurityProtocolType)192 | (SecurityProtocolType)768 | (SecurityProtocolType)3072;
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string LoademailByAD(string domain, string username) {
            return base.Channel.LoademailByAD(domain, username);
        }
        
        public string LoademailByAD2(string domain, string username) {
            return base.Channel.LoademailByAD2(domain, username);
        }
        
        public bool CheckAD_Multiserver(string domain, string username, string pwd) {
            return base.Channel.CheckAD_Multiserver(domain, username, pwd);
        }
        
        public bool CheckAD(string domain, string username, string pwd) {
            return base.Channel.CheckAD(domain, username, pwd);
        }
        
        public bool CheckAD_old(string domain, string username, string pwd) {
            return base.Channel.CheckAD_old(domain, username, pwd);
        }
        
        public string CheckSysUserLoginV2(string SystemID, string SafeCode, string UserID, string EncodedUserPwd) {
            return base.Channel.CheckSysUserLoginV2(SystemID, SafeCode, UserID, EncodedUserPwd);
        }
        
        public string CheckSysUserLogin(string SystemID, string SafeCode, string UserID, string UserPwd) {
            return base.Channel.CheckSysUserLogin(SystemID, SafeCode, UserID, UserPwd);
        }
        
        public string CheckUserAction(string SystemID, string SafeCode, string UserID, string ActionID) {
            return base.Channel.CheckUserAction(SystemID, SafeCode, UserID, ActionID);
        }
        
        public string CheckUserActionSimply(string SystemID, string SafeCode, string UserID, string ActionID) {
            return base.Channel.CheckUserActionSimply(SystemID, SafeCode, UserID, ActionID);
        }
        
        public string GetUserSystem01(string SystemID, string SafeCode, string UserID) {
            return base.Channel.GetUserSystem01(SystemID, SafeCode, UserID);
        }
        
        public string GetUserGroup01(string SystemID, string SafeCode, string ActGrpID, string UserID) {
            return base.Channel.GetUserGroup01(SystemID, SafeCode, ActGrpID, UserID);
        }
        
        public string ChangeUserPwd(string SystemID, string SafeCode, string UserID, string OldPwd, string NewPwd) {
            return base.Channel.ChangeUserPwd(SystemID, SafeCode, UserID, OldPwd, NewPwd);
        }
        
        public string ChangeUserGlobalPwd(string UserID, string OldPwd, string NewPwd) {
            return base.Channel.ChangeUserGlobalPwd(UserID, OldPwd, NewPwd);
        }
        
        public System.Data.DataSet GetUserInfoByUserID(string UserID) {
            return base.Channel.GetUserInfoByUserID(UserID);
        }
        
        public System.Data.DataSet GetUserDetailByUserID(string UserID) {
            return base.Channel.GetUserDetailByUserID(UserID);
        }
        
        public System.Data.DataSet GetUserInfoByUserAD(string UserAD) {
            return base.Channel.GetUserInfoByUserAD(UserAD);
        }
        
        public System.Data.DataSet GetUserDetailByUserAD(string UserAD) {
            return base.Channel.GetUserDetailByUserAD(UserAD);
        }
        
        public System.Data.DataSet GetSysUserByRoleID(string SystemID, string SafeCode, string RoleID) {
            return base.Channel.GetSysUserByRoleID(SystemID, SafeCode, RoleID);
        }
        
        public string CheckUserGlobalPwd(string UserID, string UserPwd) {
            return base.Channel.CheckUserGlobalPwd(UserID, UserPwd);
        }
        
        public string GetServerIP() {
            return base.Channel.GetServerIP();
        }
        
        public System.Data.DataSet GetLeaveEmp(string SiteCode, string CreateDate_s, string CreateDate_e) {
            return base.Channel.GetLeaveEmp(SiteCode, CreateDate_s, CreateDate_e);
        }
        
        public bool GeUserDomain(string userAD) {
            return base.Channel.GeUserDomain(userAD);
        }
    }
}
