//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGui.ISFReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISFReference.ISFServiceSoap")]
    public interface ISFServiceSoap {
        
        // CODEGEN: Generating message contract since element name dataXml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendAir", ReplyAction="*")]
        WebGui.ISFReference.SendAirResponse SendAir(WebGui.ISFReference.SendAirRequest request);
        
        // CODEGEN: Generating message contract since element name filePath from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOceanFromPath", ReplyAction="*")]
        WebGui.ISFReference.SendOceanFromPathResponse SendOceanFromPath(WebGui.ISFReference.SendOceanFromPathRequest request);
        
        // CODEGEN: Generating message contract since element name dataXml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOcean", ReplyAction="*")]
        WebGui.ISFReference.SendOceanResponse SendOcean(WebGui.ISFReference.SendOceanRequest request);
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        WebGui.ISFReference.LoginResponse Login(WebGui.ISFReference.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Logout", ReplyAction="*")]
        void Logout();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendAirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendAir", Namespace="http://tempuri.org/", Order=0)]
        public WebGui.ISFReference.SendAirRequestBody Body;
        
        public SendAirRequest() {
        }
        
        public SendAirRequest(WebGui.ISFReference.SendAirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendAirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dataXml;
        
        public SendAirRequestBody() {
        }
        
        public SendAirRequestBody(string dataXml) {
            this.dataXml = dataXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendAirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendAirResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebGui.ISFReference.SendAirResponseBody Body;
        
        public SendAirResponse() {
        }
        
        public SendAirResponse(WebGui.ISFReference.SendAirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendAirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendAirResult;
        
        public SendAirResponseBody() {
        }
        
        public SendAirResponseBody(string SendAirResult) {
            this.SendAirResult = SendAirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOceanFromPathRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOceanFromPath", Namespace="http://tempuri.org/", Order=0)]
        public WebGui.ISFReference.SendOceanFromPathRequestBody Body;
        
        public SendOceanFromPathRequest() {
        }
        
        public SendOceanFromPathRequest(WebGui.ISFReference.SendOceanFromPathRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendOceanFromPathRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string filePath;
        
        public SendOceanFromPathRequestBody() {
        }
        
        public SendOceanFromPathRequestBody(string filePath) {
            this.filePath = filePath;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOceanFromPathResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOceanFromPathResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebGui.ISFReference.SendOceanFromPathResponseBody Body;
        
        public SendOceanFromPathResponse() {
        }
        
        public SendOceanFromPathResponse(WebGui.ISFReference.SendOceanFromPathResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendOceanFromPathResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendOceanFromPathResult;
        
        public SendOceanFromPathResponseBody() {
        }
        
        public SendOceanFromPathResponseBody(string SendOceanFromPathResult) {
            this.SendOceanFromPathResult = SendOceanFromPathResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOceanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOcean", Namespace="http://tempuri.org/", Order=0)]
        public WebGui.ISFReference.SendOceanRequestBody Body;
        
        public SendOceanRequest() {
        }
        
        public SendOceanRequest(WebGui.ISFReference.SendOceanRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendOceanRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string dataXml;
        
        public SendOceanRequestBody() {
        }
        
        public SendOceanRequestBody(string dataXml) {
            this.dataXml = dataXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOceanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOceanResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebGui.ISFReference.SendOceanResponseBody Body;
        
        public SendOceanResponse() {
        }
        
        public SendOceanResponse(WebGui.ISFReference.SendOceanResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendOceanResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendOceanResult;
        
        public SendOceanResponseBody() {
        }
        
        public SendOceanResponseBody(string SendOceanResult) {
            this.SendOceanResult = SendOceanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public WebGui.ISFReference.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(WebGui.ISFReference.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string user, string password) {
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebGui.ISFReference.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(WebGui.ISFReference.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISFServiceSoapChannel : WebGui.ISFReference.ISFServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SFServiceSoapClient : System.ServiceModel.ClientBase<WebGui.ISFReference.ISFServiceSoap>, WebGui.ISFReference.ISFServiceSoap {
        
        public SFServiceSoapClient() {
        }
        
        public SFServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SFServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SFServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SFServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebGui.ISFReference.SendAirResponse WebGui.ISFReference.ISFServiceSoap.SendAir(WebGui.ISFReference.SendAirRequest request) {
            return base.Channel.SendAir(request);
        }
        
        public string SendAir(string dataXml) {
            WebGui.ISFReference.SendAirRequest inValue = new WebGui.ISFReference.SendAirRequest();
            inValue.Body = new WebGui.ISFReference.SendAirRequestBody();
            inValue.Body.dataXml = dataXml;
            WebGui.ISFReference.SendAirResponse retVal = ((WebGui.ISFReference.ISFServiceSoap)(this)).SendAir(inValue);
            return retVal.Body.SendAirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebGui.ISFReference.SendOceanFromPathResponse WebGui.ISFReference.ISFServiceSoap.SendOceanFromPath(WebGui.ISFReference.SendOceanFromPathRequest request) {
            return base.Channel.SendOceanFromPath(request);
        }
        
        public string SendOceanFromPath(string filePath) {
            WebGui.ISFReference.SendOceanFromPathRequest inValue = new WebGui.ISFReference.SendOceanFromPathRequest();
            inValue.Body = new WebGui.ISFReference.SendOceanFromPathRequestBody();
            inValue.Body.filePath = filePath;
            WebGui.ISFReference.SendOceanFromPathResponse retVal = ((WebGui.ISFReference.ISFServiceSoap)(this)).SendOceanFromPath(inValue);
            return retVal.Body.SendOceanFromPathResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebGui.ISFReference.SendOceanResponse WebGui.ISFReference.ISFServiceSoap.SendOcean(WebGui.ISFReference.SendOceanRequest request) {
            return base.Channel.SendOcean(request);
        }
        
        public string SendOcean(string dataXml) {
            WebGui.ISFReference.SendOceanRequest inValue = new WebGui.ISFReference.SendOceanRequest();
            inValue.Body = new WebGui.ISFReference.SendOceanRequestBody();
            inValue.Body.dataXml = dataXml;
            WebGui.ISFReference.SendOceanResponse retVal = ((WebGui.ISFReference.ISFServiceSoap)(this)).SendOcean(inValue);
            return retVal.Body.SendOceanResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebGui.ISFReference.LoginResponse WebGui.ISFReference.ISFServiceSoap.Login(WebGui.ISFReference.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string user, string password) {
            WebGui.ISFReference.LoginRequest inValue = new WebGui.ISFReference.LoginRequest();
            inValue.Body = new WebGui.ISFReference.LoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            WebGui.ISFReference.LoginResponse retVal = ((WebGui.ISFReference.ISFServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        public void Logout() {
            base.Channel.Logout();
        }
    }
}
