//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36399
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGui.TransferOperation {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TPVInboundOrderRequest", Namespace="http://schemas.datacontract.org/2004/07/CommonClassLibrary.model.TPV")]
    [System.SerializableAttribute()]
    public partial class TPVInboundOrderRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AtaPortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarrierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContainerNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestionationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EtaHubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EtaPortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EtaTerminalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EtdChinaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebGui.TransferOperation.Item[] ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SealNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VesselField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtaPort {
            get {
                return this.AtaPortField;
            }
            set {
                if ((object.ReferenceEquals(this.AtaPortField, value) != true)) {
                    this.AtaPortField = value;
                    this.RaisePropertyChanged("AtaPort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Carrier {
            get {
                return this.CarrierField;
            }
            set {
                if ((object.ReferenceEquals(this.CarrierField, value) != true)) {
                    this.CarrierField = value;
                    this.RaisePropertyChanged("Carrier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContainerNo {
            get {
                return this.ContainerNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContainerNoField, value) != true)) {
                    this.ContainerNoField = value;
                    this.RaisePropertyChanged("ContainerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destionation {
            get {
                return this.DestionationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestionationField, value) != true)) {
                    this.DestionationField = value;
                    this.RaisePropertyChanged("Destionation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EtaHub {
            get {
                return this.EtaHubField;
            }
            set {
                if ((object.ReferenceEquals(this.EtaHubField, value) != true)) {
                    this.EtaHubField = value;
                    this.RaisePropertyChanged("EtaHub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EtaPort {
            get {
                return this.EtaPortField;
            }
            set {
                if ((object.ReferenceEquals(this.EtaPortField, value) != true)) {
                    this.EtaPortField = value;
                    this.RaisePropertyChanged("EtaPort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EtaTerminal {
            get {
                return this.EtaTerminalField;
            }
            set {
                if ((object.ReferenceEquals(this.EtaTerminalField, value) != true)) {
                    this.EtaTerminalField = value;
                    this.RaisePropertyChanged("EtaTerminal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EtdChina {
            get {
                return this.EtdChinaField;
            }
            set {
                if ((object.ReferenceEquals(this.EtdChinaField, value) != true)) {
                    this.EtdChinaField = value;
                    this.RaisePropertyChanged("EtdChina");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebGui.TransferOperation.Item[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SealNo {
            get {
                return this.SealNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SealNoField, value) != true)) {
                    this.SealNoField = value;
                    this.RaisePropertyChanged("SealNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipmentId {
            get {
                return this.ShipmentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipmentIdField, value) != true)) {
                    this.ShipmentIdField = value;
                    this.RaisePropertyChanged("ShipmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vessel {
            get {
                return this.VesselField;
            }
            set {
                if ((object.ReferenceEquals(this.VesselField, value) != true)) {
                    this.VesselField = value;
                    this.RaisePropertyChanged("Vessel");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/CommonClassLibrary.model.TPV")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QtyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((object.ReferenceEquals(this.QtyField, value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/CommonClassLibrary.model.Export.DC")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WISEPOIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyIDField, value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrMessage {
            get {
                return this.ErrMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrMessageField, value) != true)) {
                    this.ErrMessageField = value;
                    this.RaisePropertyChanged("ErrMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderNo {
            get {
                return this.OrderNoField;
            }
            set {
                if ((this.OrderNoField.Equals(value) != true)) {
                    this.OrderNoField = value;
                    this.RaisePropertyChanged("OrderNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoNo {
            get {
                return this.PoNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PoNoField, value) != true)) {
                    this.PoNoField = value;
                    this.RaisePropertyChanged("PoNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNo {
            get {
                return this.ReferenceNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNoField, value) != true)) {
                    this.ReferenceNoField = value;
                    this.RaisePropertyChanged("ReferenceNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WISEPOID {
            get {
                return this.WISEPOIDField;
            }
            set {
                if ((object.ReferenceEquals(this.WISEPOIDField, value) != true)) {
                    this.WISEPOIDField = value;
                    this.RaisePropertyChanged("WISEPOID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TruckerInfomation", Namespace="http://schemas.datacontract.org/2004/07/CommonClassLibrary.model.TPV")]
    [System.SerializableAttribute()]
    public partial class TruckerInfomation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AtYardDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CardIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContainerNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DriverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EachCntrQtyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmptyReturnDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GateInDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GateOutDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeavyPickupDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewEtaHubField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewTrailerNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputFormatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutputImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PodDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PortDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PortTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceivedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RemarkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReserveNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipmentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerminDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarehouseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AtYardDate {
            get {
                return this.AtYardDateField;
            }
            set {
                if ((object.ReferenceEquals(this.AtYardDateField, value) != true)) {
                    this.AtYardDateField = value;
                    this.RaisePropertyChanged("AtYardDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CardId {
            get {
                return this.CardIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CardIdField, value) != true)) {
                    this.CardIdField = value;
                    this.RaisePropertyChanged("CardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContainerNo {
            get {
                return this.ContainerNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContainerNoField, value) != true)) {
                    this.ContainerNoField = value;
                    this.RaisePropertyChanged("ContainerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Driver {
            get {
                return this.DriverField;
            }
            set {
                if ((object.ReferenceEquals(this.DriverField, value) != true)) {
                    this.DriverField = value;
                    this.RaisePropertyChanged("Driver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EachCntrQty {
            get {
                return this.EachCntrQtyField;
            }
            set {
                if ((object.ReferenceEquals(this.EachCntrQtyField, value) != true)) {
                    this.EachCntrQtyField = value;
                    this.RaisePropertyChanged("EachCntrQty");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmptyReturnDate {
            get {
                return this.EmptyReturnDateField;
            }
            set {
                if ((object.ReferenceEquals(this.EmptyReturnDateField, value) != true)) {
                    this.EmptyReturnDateField = value;
                    this.RaisePropertyChanged("EmptyReturnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GateInDate {
            get {
                return this.GateInDateField;
            }
            set {
                if ((object.ReferenceEquals(this.GateInDateField, value) != true)) {
                    this.GateInDateField = value;
                    this.RaisePropertyChanged("GateInDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GateOutDate {
            get {
                return this.GateOutDateField;
            }
            set {
                if ((object.ReferenceEquals(this.GateOutDateField, value) != true)) {
                    this.GateOutDateField = value;
                    this.RaisePropertyChanged("GateOutDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HeavyPickupDate {
            get {
                return this.HeavyPickupDateField;
            }
            set {
                if ((object.ReferenceEquals(this.HeavyPickupDateField, value) != true)) {
                    this.HeavyPickupDateField = value;
                    this.RaisePropertyChanged("HeavyPickupDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mode {
            get {
                return this.ModeField;
            }
            set {
                if ((object.ReferenceEquals(this.ModeField, value) != true)) {
                    this.ModeField = value;
                    this.RaisePropertyChanged("Mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewEtaHub {
            get {
                return this.NewEtaHubField;
            }
            set {
                if ((object.ReferenceEquals(this.NewEtaHubField, value) != true)) {
                    this.NewEtaHubField = value;
                    this.RaisePropertyChanged("NewEtaHub");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewTrailerNo {
            get {
                return this.NewTrailerNoField;
            }
            set {
                if ((object.ReferenceEquals(this.NewTrailerNoField, value) != true)) {
                    this.NewTrailerNoField = value;
                    this.RaisePropertyChanged("NewTrailerNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputFormat {
            get {
                return this.OutputFormatField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputFormatField, value) != true)) {
                    this.OutputFormatField = value;
                    this.RaisePropertyChanged("OutputFormat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutputImage {
            get {
                return this.OutputImageField;
            }
            set {
                if ((object.ReferenceEquals(this.OutputImageField, value) != true)) {
                    this.OutputImageField = value;
                    this.RaisePropertyChanged("OutputImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PodDate {
            get {
                return this.PodDateField;
            }
            set {
                if ((object.ReferenceEquals(this.PodDateField, value) != true)) {
                    this.PodDateField = value;
                    this.RaisePropertyChanged("PodDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortDate {
            get {
                return this.PortDateField;
            }
            set {
                if ((object.ReferenceEquals(this.PortDateField, value) != true)) {
                    this.PortDateField = value;
                    this.RaisePropertyChanged("PortDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortTime {
            get {
                return this.PortTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.PortTimeField, value) != true)) {
                    this.PortTimeField = value;
                    this.RaisePropertyChanged("PortTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceivedDate {
            get {
                return this.ReceivedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceivedDateField, value) != true)) {
                    this.ReceivedDateField = value;
                    this.RaisePropertyChanged("ReceivedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Remark {
            get {
                return this.RemarkField;
            }
            set {
                if ((object.ReferenceEquals(this.RemarkField, value) != true)) {
                    this.RemarkField = value;
                    this.RaisePropertyChanged("Remark");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReserveNo {
            get {
                return this.ReserveNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReserveNoField, value) != true)) {
                    this.ReserveNoField = value;
                    this.RaisePropertyChanged("ReserveNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipDate {
            get {
                return this.ShipDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipDateField, value) != true)) {
                    this.ShipDateField = value;
                    this.RaisePropertyChanged("ShipDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipmentId {
            get {
                return this.ShipmentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipmentIdField, value) != true)) {
                    this.ShipmentIdField = value;
                    this.RaisePropertyChanged("ShipmentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TerminDate {
            get {
                return this.TerminDateField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminDateField, value) != true)) {
                    this.TerminDateField = value;
                    this.RaisePropertyChanged("TerminDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Warehouse {
            get {
                return this.WarehouseField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseField, value) != true)) {
                    this.WarehouseField = value;
                    this.RaisePropertyChanged("Warehouse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransferOperation.IInboundTPVService")]
    public interface IInboundTPVService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInboundTPVService/DoWork", ReplyAction="http://tempuri.org/IInboundTPVService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInboundTPVService/TPVInboundOrderWISE", ReplyAction="http://tempuri.org/IInboundTPVService/TPVInboundOrderWISEResponse")]
        WebGui.TransferOperation.Response TPVInboundOrderWISE(WebGui.TransferOperation.TPVInboundOrderRequest data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInboundTPVService/TPVAllDataResponse", ReplyAction="http://tempuri.org/IInboundTPVService/TPVAllDataResponseResponse")]
        WebGui.TransferOperation.Response TPVAllDataResponse(WebGui.TransferOperation.TruckerInfomation data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInboundTPVServiceChannel : WebGui.TransferOperation.IInboundTPVService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InboundTPVServiceClient : System.ServiceModel.ClientBase<WebGui.TransferOperation.IInboundTPVService>, WebGui.TransferOperation.IInboundTPVService {
        
        public InboundTPVServiceClient() {
        }
        
        public InboundTPVServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InboundTPVServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InboundTPVServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InboundTPVServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public WebGui.TransferOperation.Response TPVInboundOrderWISE(WebGui.TransferOperation.TPVInboundOrderRequest data) {
            return base.Channel.TPVInboundOrderWISE(data);
        }
        
        public WebGui.TransferOperation.Response TPVAllDataResponse(WebGui.TransferOperation.TruckerInfomation data) {
            return base.Channel.TPVAllDataResponse(data);
        }
    }
}
