IF OBJECT_ID('dbo.SMSMI', 'U') IS NOT NULL 
 DROP TABLE dbo.SMSMI; 
CREATE TABLE [dbo].[SMSMI](
	[U_ID] [nvarchar](50) NOT NULL,
	[LIGHT] [nvarchar](1000) NULL,
	[MONTH] [nvarchar](10) NULL,
	[GROUP_ID] [nvarchar](10) NULL,
	[CMP] [nvarchar](10) NULL,
	[STN] [nvarchar](10) NULL,
	[DEP] [nvarchar](10) NULL,
	[SHIPMENT_ID] [nvarchar](20) NULL,
	[TRAN_TYPE] [nvarchar](1) NULL,
	[STATUS] [nvarchar](1) NULL,
	[DN_ETD] [date] NULL,
	[COMBINE_INFO] [nvarchar](3000) NULL,
	[MARKS] [nvarchar](3000) NULL,
	[GOODS] [nvarchar](2000) NULL,
	[LGOODS] [nvarchar](2000) NULL,
	[BL_RMK] [nvarchar](3000) NULL,
	[INSTRUCTION] [nvarchar](2000) NULL,
	[BOOKING_INFO] [nvarchar](300) NULL,
	[ABNORMAL_RMK] [nvarchar](1000) NULL,
	[LSP_ABNORMAL_RMK] [nvarchar](1000) NULL,
	[PRODUCTION_DATE] [date] NULL,
	[PRIORITY] [int] NULL,
	[PORT_FREE_TIME] [int] NULL,
	[FACT_FREE_TIME] [int] NULL,
	[FREIGHT_CUR] [nvarchar](3) NULL,
	[FREIGHT_AMT] [decimal](10, 2) NULL,
	[CUR] [nvarchar](3) NULL,
	[GVALUE] [decimal](10, 2) NULL,
	[CNT20] [decimal](10, 0) NULL,
	[CNT40] [decimal](10, 0) NULL,
	[CNT40HQ] [decimal](10, 0) NULL,
	[CNT_TYPE] [nvarchar](5) NULL,
	[CNT_NUMBER] [decimal](10, 0) NULL,
	[INSURANCE_AMT] [decimal](10, 2) NULL,
	[PKG_NUM] [decimal](10, 0) NULL,
	[PKG_UNIT] [nvarchar](20) NULL,
	[PKG_UNIT_DESC] [nvarchar](100) NULL,
	[GW] [decimal](10, 3) NULL,
	[GWU] [nvarchar](3) NULL,
	[CBM] [decimal](10, 4) NULL,
	[WEEKLY] [decimal](10, 0) NULL,
	[YEAR] [decimal](10, 0) NULL,
	[TRADE_TERM] [nvarchar](3) NULL,
	[TRADETERM_DESCP] [nvarchar](30) NULL,
	[INCOTERM_CD] [nvarchar](3) NULL,
	[INCOTERM_DESCP] [nvarchar](30) NULL,
	[LOADING_FROM] [nvarchar](5) NULL,
	[LOADING_TO] [nvarchar](5) NULL,
	[PICKUP_CDATE] [date] NULL,
	[CARRIER] [nvarchar](20) NULL,
	[CARRIER_NM] [nvarchar](70) NULL,
	[SCAC_CD] [nvarchar](20) NULL,
	[FRT_TERM] [nvarchar](2) NULL,
	[CON_FREE_TIME] [int] NULL,
	[MASTER_NO] [nvarchar](20) NULL,
	[HOUSE_NO] [nvarchar](20) NULL,
	[SVC_CONTACT] [nvarchar](20) NULL,
	[WH_TIME] [datetime] NULL,
	[POR_CD] [nvarchar](5) NULL,
	[POR_CNTY] [nvarchar](2) NULL,
	[POR_NAME] [nvarchar](30) NULL,
	[IB_WINDOW] [nvarchar](200) NULL,
	[FACT_TIME] [datetime] NULL,
	[POL_CD] [nvarchar](5) NULL,
	[POL_CNTY] [nvarchar](2) NULL,
	[POL_NAME] [nvarchar](30) NULL,
	[PORT_ETA] [date] NULL,
	[EMPTY_TIME] [datetime] NULL,
	[POD_CD] [nvarchar](5) NULL,
	[POD_CNTY] [nvarchar](2) NULL,
	[POD_NAME] [nvarchar](30) NULL,
	[PORT_ATA] [datetime] NULL,
	[BACK_LOCATION] [nvarchar](50) NULL,
	[DEST_CD] [nvarchar](5) NULL,
	[DEST_CNTY] [nvarchar](2) NULL,
	[DEST_NAME] [nvarchar](30) NULL,
	[PORT_RLS_DATE] [datetime] NULL,
	[WM_CUT_DATE] [datetime] NULL,
	[VESSEL1] [nvarchar](30) NULL,
	[VOYAGE1] [nvarchar](12) NULL,
	[ETD1] [date] NULL,
	[ETA1] [date] NULL,
	[VESSEL2] [nvarchar](30) NULL,
	[VOYAGE2] [nvarchar](12) NULL,
	[ETD2] [date] NULL,
	[ETA2] [date] NULL,
	[VESSEL3] [nvarchar](30) NULL,
	[VOYAGE3] [nvarchar](12) NULL,
	[ETD3] [date] NULL,
	[ETA3] [date] NULL,
	[VESSEL4] [nvarchar](30) NULL,
	[VOYAGE4] [nvarchar](12) NULL,
	[ETD4] [date] NULL,
	[ETA4] [date] NULL,
	[ETD] [date] NULL,
	[ETA] [date] NULL,
	[ATP] [date] NULL,
	[ATD] [date] NULL,
	[ATA] [date] NULL,
	[OEXPORTER] [nvarchar](10) NULL,
	[OEXPORTER_NM] [nvarchar](70) NULL,
	[OEXPORTER_ADDR] [nvarchar](140) NULL,
	[OIMPORTER] [nvarchar](10) NULL,
	[OIMPORTER_NM] [nvarchar](70) NULL,
	[OIMPORTER_ADDR] [nvarchar](140) NULL,
	[IMPORT_NO] [nvarchar](50) NULL,
	[DEC_NO] [nvarchar](50) NULL,
	[CER_NO] [nvarchar](50) NULL,
	[DEC_DATE] [date] NULL,
	[REL_DATE] [date] NULL,
	[INSPECTION] [nvarchar](50) NULL,
	[DEC_CUST] [text] NULL,
	[DEC_REPLY] [text] NULL,
	[TC_IMPORTER] [nvarchar](10) NULL,
	[TC_IMPORTER_NM] [nvarchar](70) NULL,
	[TC_IMPORTER_ADDR] [nvarchar](140) NULL,
	[TC_IMPORT_NO] [nvarchar](50) NULL,
	[TC_DEC_NO] [nvarchar](50) NULL,
	[TC_CER_NO] [nvarchar](50) NULL,
	[TC_DEC_DATE] [date] NULL,
	[TC_REL_DATE] [date] NULL,
	[TC_INSPECTION] [nvarchar](50) NULL,
	[TC_DEC_CUST] [text] NULL,
	[TC_DEC_REPLY] [text] NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_BY] [nvarchar](40) NULL,
	[MODIFY_DATE] [datetime] NULL,
	[MODIFY_BY] [nvarchar](40) NULL,
	[AIRLINE_CD] [nvarchar](10) NULL,
	[AIRLINE_NM] [nvarchar](70) NULL,
	[QTY] [int] NULL,
	[QTYU] [nvarchar](10) NULL,
	[VW] [decimal](10, 3) NULL,
	[OF_COST] [decimal](10, 2) NULL,
	[TRUCK_COST] [decimal](10, 2) NULL,
	[CW] [decimal](10, 3) NULL,
	[HORN] [nvarchar](1) NULL,
	[BATTERY] [nvarchar](1) NULL,
	[TRUCK_CD] [nvarchar](20) NULL,
	[O_LOCATION] [nvarchar](10) NULL,
	[CSTATUS] [nvarchar](1) NULL,
	[BSTATUS] [nvarchar](1) NULL,
	[DN_NO] [nvarchar](100) NULL,
	[LOT_NO] [nvarchar](20) NULL,
	[BL_WIN] [nvarchar](40) NULL,
	[TERMINAL_CD] [nvarchar](30) NULL,
	[TERMINAL_NM] [nvarchar](70) NULL,
	[HS_CODE] [nvarchar](20) NULL,
	[HS_CODE_NO] [nvarchar](20) NULL,
	[TC_HS_CODE] [nvarchar](20) NULL,
	[TC_HS_CODE_NO] [nvarchar](20) NULL,
	[PRODUCT_TYPE] [nvarchar](20) NULL,
	[CONTAINER_YARD_CD] [nvarchar](20) NULL,
	[CONTAINER_YARD_NM] [nvarchar](300) NULL,
	[EXTRA_SRV] [nvarchar](50) NULL,
	[EXTRA_MEMO] [nvarchar](50) NULL,
	[FORK] [decimal](5, 0) NULL,
	[O_UID] [nvarchar](50) NULL,
	[POL1] [nvarchar](5) NULL,
	[POL_NM1] [nvarchar](70) NULL,
	[POD1] [nvarchar](5) NULL,
	[POD_NM1] [nvarchar](70) NULL,
	[TRAN_TYPE1] [nvarchar](1) NULL,
	[DEP_ADDR_CD1] [nvarchar](10) NULL,
	[DEP_ADDR1] [nvarchar](200) NULL,
	[TRUCKER1] [nvarchar](20) NULL,
	[TRUCKER_NM1] [nvarchar](70) NULL,
	[POL2] [nvarchar](5) NULL,
	[POL_NM2] [nvarchar](70) NULL,
	[POD2] [nvarchar](5) NULL,
	[POD_NM2] [nvarchar](70) NULL,
	[TRAN_TYPE2] [nvarchar](1) NULL,
	[DEP_ADDR_CD2] [nvarchar](10) NULL,
	[DEP_ADDR2] [nvarchar](200) NULL,
	[TRUCKER2] [nvarchar](20) NULL,
	[TRUCKER_NM2] [nvarchar](70) NULL,
	[POL3] [nvarchar](5) NULL,
	[POL_NM3] [nvarchar](70) NULL,
	[POD3] [nvarchar](5) NULL,
	[POD_NM3] [nvarchar](70) NULL,
	[TRAN_TYPE3] [nvarchar](1) NULL,
	[DEP_ADDR_CD3] [nvarchar](10) NULL,
	[DEP_ADDR3] [nvarchar](200) NULL,
	[TRUCKER3] [nvarchar](20) NULL,
	[TRUCKER_NM3] [nvarchar](70) NULL,
	[T_ATD1] [datetime] NULL,
	[T_ETD1] [datetime] NULL,
	[T_ETA1] [datetime] NULL,
	[T_ATA1] [datetime] NULL,
	[T_ATD2] [datetime] NULL,
	[T_ETD2] [datetime] NULL,
	[T_ETA2] [datetime] NULL,
	[T_ATA2] [datetime] NULL,
	[T_ATD3] [datetime] NULL,
	[T_ETD3] [datetime] NULL,
	[T_ETA3] [datetime] NULL,
	[T_ATA3] [datetime] NULL,
	[POD_MDATE] [datetime] NULL,
	[HTS_CODE] [nvarchar](50) NULL,
	[COUNTRY] [nvarchar](5) NULL,
	[DEST_REGION] [nvarchar](5) NULL,
	[CNTR_INFO] [nvarchar](500) NULL,
	[INBOUND_PO_NO] [nvarchar](30) NULL,
	[TC_IMPORTER_REMARK] [nvarchar](2000) NULL,
	[CC_IMPORTER_REMARK] [nvarchar](2000) NULL,
 CONSTRAINT [PK_SMSMI] PRIMARY KEY CLUSTERED 
(
	[U_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

IF OBJECT_ID('dbo.SMIDN', 'U') IS NOT NULL 
 DROP TABLE dbo.SMIDN; 
CREATE TABLE [dbo].[SMIDN](
	[U_ID] [nvarchar](50) NULL,
	[GROUP_ID] [nvarchar](10) NULL,
	[CMP] [nvarchar](10) NULL,
	[STN] [nvarchar](10) NULL,
	[DEP] [nvarchar](10) NULL,
	[SHIPMENT_ID] [nvarchar](20) NULL,
	[DN_NO] [nvarchar](20) NULL,
	[INV_NO] [nvarchar](20) NULL,
	[NW] [numeric](10, 3) NULL,
	[GW] [numeric](10, 3) NULL,
	[GWU] [nvarchar](3) NULL,
	[CBM] [numeric](10, 3) NULL,
	[CBMU] [nvarchar](3) NULL,
	[QTY] [numeric](10, 3) NULL,
	[QTYU] [nvarchar](3) NULL,
	[PKG_NUM] [numeric](10, 0) NULL,
	[PKG_UNIT] [nvarchar](20) NULL,
	[PKG_UNIT_DESC] [nvarchar](100) NULL,
	[CNT20] [numeric](3, 0) NULL,
	[CNT40] [numeric](3, 0) NULL,
	[CNT40HQ] [numeric](3, 0) NULL,
	[OTH_CNT_TYPE] [nvarchar](20) NULL,
	[OTH_CNT_NUM] [numeric](3, 0) NULL,
	[IMPORT_NO] [nvarchar](50) NULL,
	[DEC_NO] [nvarchar](50) NULL,
	[CER_NO] [nvarchar](50) NULL,
	[DEC_DATE] [datetime] NULL,
	[REL_DATE] [datetime] NULL,
	[INSPECTION] [nvarchar](1) NULL DEFAULT ('N'),
	[DEC_CUST] [text] NULL,
	[DEC_REPLY] [text] NULL,
	[TC_IMPORT_NO] [nvarchar](50) NULL,
	[TC_DEC_NO] [nvarchar](50) NULL,
	[TC_CER_NO] [nvarchar](50) NULL,
	[TC_DEC_DATE] [datetime] NULL,
	[TC_REL_DATE] [datetime] NULL,
	[TC_INSPECTION] [nvarchar](50) NULL DEFAULT ('N'),
	[TC_DEC_CUST] [text] NULL,
	[TC_DEC_REPLY] [text] NULL,
	[DLV_AREA] [nvarchar](20) NULL,
	[DLV_AREA_NM] [nvarchar](70) NULL,
	[ADDR_CODE] [nvarchar](10) NULL,
	[DLV_ADDR] [nvarchar](350) NULL,
	[RESERVE_NO] [nvarchar](20) NULL,
	[WS_CD] [nvarchar](10) NULL,
	[DIVISION_DESCP] [nvarchar](20) NULL,
	[ICDF] [nvarchar](1) NULL DEFAULT ('N'),
	[TC_ICDF] [nvarchar](1) NULL DEFAULT ('N'),
	[INV_PRICE] [decimal](10, 2) NULL,
	[INV_CUR] [nvarchar](3) NULL,
	[INSERT_NO] [nvarchar](50) NULL,
	[HS_QTY] [int] NULL,
	[TC_HS_QTY] [int] NULL,
	[CNTRY_CD] [nvarchar](2) NULL,
	[TC_CNTRY_CD] [nvarchar](20) NULL,
	[PD_QTY] [int] NULL,
	[PICKUP_CDATE] [datetime] NULL,
	[STORAGE_DUE_DATE] [date] NULL,
	[DISCHARGE_DATE] [date] NULL,
	[SCMREQUEST_DATE] [datetime] NULL,
	[PRIORITY] [int] NULL,
	[FOB_AMT] [numeric](18, 2) NULL,
	[CIF_AMT] [numeric](18, 2) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


IF OBJECT_ID('dbo.SMIDNP', 'U') IS NOT NULL 
 DROP TABLE dbo.SMIDNP; 
CREATE TABLE [dbo].[SMIDNP](
	[U_ID] [nvarchar](50) NULL,
	[U_FID] [nvarchar](50) NULL,
	[SHIPMENT_ID] [nvarchar](20) NULL,
	[DN_NO] [nvarchar](20) NULL,
	[INV_NO] [nvarchar](20) NULL,
	[OPART_NO] [nvarchar](18) NULL,
	[IPART_NO] [nvarchar](18) NULL,
	[GOODS_DESCP] [nvarchar](40) NULL,
	[PROD_DESCP] [nvarchar](50) NULL,
	[QTY] [numeric](10, 3) NULL,
	[GW] [numeric](10, 3) NULL,
	[CBM] [numeric](10, 3) NULL,
	[CNTR_TYPE] [nvarchar](20) NULL,
	[CNTR_NO] [nvarchar](20) NULL,
	[SEAL_NO1] [nvarchar](20) NULL,
	[SEAL_NO2] [nvarchar](20) NULL,
	[DLV_AREA] [nvarchar](20) NULL,
	[DLV_AREA_NM] [nvarchar](70) NULL,
	[ADDR_CODE] [nvarchar](10) NULL,
	[DLV_ADDR] [nvarchar](350) NULL
) ON [PRIMARY]

IF OBJECT_ID('dbo.SMICNTR', 'U') IS NOT NULL 
 DROP TABLE dbo.SMICNTR; 
 CREATE TABLE [dbo].[SMICNTR](
	[U_ID] [nvarchar](50) NOT NULL,
	[SHIPMENT_ID] [nvarchar](20) NULL,
	[CMP] [nvarchar](10) NULL,
	[CNTR_NO] [nvarchar](20) NULL,
	[CNTR_TYPE] [nvarchar](10) NULL,
	[SEAL_NO1] [nvarchar](20) NULL,
	[SEAL_NO2] [nvarchar](20) NULL,
	[DN_NO] [nvarchar](500) NULL,
	[DIVISION_DESCP] [nvarchar](500) NULL,
	[QTY] [int] NULL,
	[QTYU] [nvarchar](3) NULL,
	[GW] [numeric](10, 3) NULL,
	[GWU] [nvarchar](3) NULL,
	[CBM] [numeric](10, 4) NULL,
	[IMPORT_NO] [nvarchar](50) NULL,
	[DEC_NO] [nvarchar](50) NULL,
	[CER_NO] [nvarchar](50) NULL,
	[DEC_DATE] [datetime] NULL,
	[REL_DATE] [datetime] NULL,
	[INSPECTION] [nvarchar](1) NULL CONSTRAINT [DF__SMICNTR__INSPECT__7B663F43]  DEFAULT ('N'),
	[DEC_CUST] [text] NULL,
	[DEC_REPLY] [text] NULL,
	[TC_IMPORT_NO] [nvarchar](50) NULL,
	[TC_DEC_NO] [nvarchar](50) NULL,
	[TC_CER_NO] [nvarchar](50) NULL,
	[TC_DEC_DATE] [datetime] NULL,
	[TC_REL_DATE] [datetime] NULL,
	[TC_INSPECTION] [nvarchar](1) NULL CONSTRAINT [DF__SMICNTR__TC_INSP__7F36D027]  DEFAULT ('N'),
	[TC_DEC_CUST] [text] NULL,
	[TC_DEC_REPLY] [text] NULL,
	[RESERVE_NO] [nvarchar](20) NULL,
	[DLV_AREA] [nvarchar](20) NULL,
	[DLV_AREA_NM] [nvarchar](70) NULL,
	[ADDR_CODE] [nvarchar](10) NULL,
	[DLV_ADDR] [nvarchar](350) NULL,
	[POL1] [nvarchar](5) NULL,
	[POL_NM1] [nvarchar](70) NULL,
	[POD1] [nvarchar](5) NULL,
	[POD_NM1] [nvarchar](70) NULL,
	[TRAN_TYPE1] [nvarchar](1) NULL,
	[DEP_ADDR1] [nvarchar](200) NULL,
	[TRUCKER1] [nvarchar](20) NULL,
	[TRUCKER_NM1] [nvarchar](70) NULL,
	[T_ATD1] [datetime] NULL,
	[T_ETD1] [datetime] NULL,
	[T_ETA1] [datetime] NULL,
	[T_ATA1] [datetime] NULL,
	[POL2] [nvarchar](5) NULL,
	[POL_NM2] [nvarchar](70) NULL,
	[POD2] [nvarchar](5) NULL,
	[POD_NM2] [nvarchar](70) NULL,
	[TRAN_TYPE2] [nvarchar](1) NULL,
	[DEP_ADDR2] [nvarchar](200) NULL,
	[TRUCKER2] [nvarchar](20) NULL,
	[TRUCKER_NM2] [nvarchar](70) NULL,
	[T_ATD2] [datetime] NULL,
	[T_ETD2] [datetime] NULL,
	[T_ETA2] [datetime] NULL,
	[T_ATA2] [datetime] NULL,
	[POL3] [nvarchar](5) NULL,
	[POL_NM3] [nvarchar](70) NULL,
	[POD3] [nvarchar](5) NULL,
	[POD_NM3] [nvarchar](70) NULL,
	[TRAN_TYPE3] [nvarchar](1) NULL,
	[DEP_ADDR3] [nvarchar](200) NULL,
	[TRUCKER3] [nvarchar](20) NULL,
	[TRUCKER_NM3] [nvarchar](70) NULL,
	[T_ATD3] [datetime] NULL,
	[T_ETD3] [datetime] NULL,
	[T_ETA3] [datetime] NULL,
	[T_ATA3] [datetime] NULL,
	[ICDF] [nvarchar](1) NULL CONSTRAINT [DF__SMICNTR__ICDF__7A721B0A]  DEFAULT ('N'),
	[TC_ICDF] [nvarchar](1) NULL CONSTRAINT [DF__SMICNTR__TC_ICDF__7E42ABEE]  DEFAULT ('N'),
	[GROUP_ID] [nvarchar](10) NULL,
	[STN] [nvarchar](10) NULL,
	[DEP] [nvarchar](10) NULL,
	[NEW_SEAL] [nvarchar](20) NULL,
	[TC_NEW_SEAL] [nvarchar](20) NULL,
	[HS_QTY] [int] NULL,
	[TC_HS_QTY] [int] NULL,
	[CNTRY_CD] [nvarchar](2) NULL,
	[BACK_LOCATION] [nvarchar](50) NULL,
	[TC_CNTRY_CD] [nvarchar](20) NULL,
	[PD_QTY] [int] NULL,
	[EMPTY_TIME] [datetime] NULL,
	[PICKUP_CDATE] [datetime] NULL,
	[DETENTION_DUE_DATE] [date] NULL,
	[DEMURRAGE_DUE_DATE] [date] NULL,
	[DISCHARGE_DATE] [date] NULL,
	[STORAGE_DUE_DATE] [date] NULL,
	[SCMREQUEST_DATE] [datetime] NULL,
	[PRIORITY] [int] NULL,
	[FOB_AMT] [numeric](18, 2) NULL,
	[CIF_AMT] [numeric](18, 2) NULL,
 CONSTRAINT [PK_SMICNTR_1] PRIMARY KEY CLUSTERED 
(
	[U_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

 IF OBJECT_ID('dbo.SMORD', 'U') IS NOT NULL 
 DROP TABLE dbo.SMORD; 
CREATE TABLE [dbo].[SMORD](
	[SHIPMENT_ID] [nvarchar](20) NULL,
	[ORD_NO] [nvarchar](20) NOT NULL,
	[TRAN_NO] [int] NULL,
	[TRAN_TYPE1] [nvarchar](1) NULL,
	[POL1] [nvarchar](5) NULL,
	[POL_NM1] [nvarchar](70) NULL,
	[POD1] [nvarchar](5) NULL,
	[POD_NM1] [nvarchar](70) NULL,
	[DEP_ADDR] [nvarchar](200) NULL,
	[TRUCKER1] [nvarchar](20) NULL,
	[TRUCKER_NM1] [nvarchar](70) NULL,
	[LIGHT] [nvarchar](1000) NULL,
	[MONTH] [nvarchar](10) NULL,
	[GROUP_ID] [nvarchar](10) NULL,
	[CMP] [nvarchar](10) NULL,
	[STN] [nvarchar](10) NULL,
	[DEP] [nvarchar](10) NULL,
	[TRAN_TYPE] [nvarchar](1) NULL,
	[STATUS] [nvarchar](1) NULL,
	[DN_ETD] [date] NULL,
	[COMBINE_INFO] [nvarchar](3000) NULL,
	[MARKS] [nvarchar](3000) NULL,
	[GOODS] [nvarchar](2000) NULL,
	[LGOODS] [nvarchar](2000) NULL,
	[BL_RMK] [nvarchar](3000) NULL,
	[INSTRUCTION] [nvarchar](2000) NULL,
	[BOOKING_INFO] [nvarchar](300) NULL,
	[ABNORMAL_RMK] [nvarchar](1000) NULL,
	[LSP_ABNORMAL_RMK] [nvarchar](1000) NULL,
	[PRODUCTION_DATE] [date] NULL,
	[PRIORITY] [int] NULL,
	[PORT_FREE_TIME] [int] NULL,
	[FACT_FREE_TIME] [int] NULL,
	[FREIGHT_CUR] [nvarchar](3) NULL,
	[FREIGHT_AMT] [decimal](10, 2) NULL,
	[CUR] [nvarchar](3) NULL,
	[GVALUE] [decimal](10, 2) NULL,
	[CNT20] [decimal](10, 0) NULL,
	[CNT40] [decimal](10, 0) NULL,
	[CNT40HQ] [decimal](10, 0) NULL,
	[CNT_TYPE] [nvarchar](5) NULL,
	[CNT_NUMBER] [decimal](10, 0) NULL,
	[INSURANCE_AMT] [decimal](10, 2) NULL,
	[PKG_NUM] [decimal](10, 0) NULL,
	[PKG_UNIT] [nvarchar](20) NULL,
	[PKG_UNIT_DESC] [nvarchar](100) NULL,
	[GW] [decimal](10, 3) NULL,
	[GWU] [nvarchar](3) NULL,
	[CBM] [decimal](10, 4) NULL,
	[WEEKLY] [decimal](10, 0) NULL,
	[YEAR] [decimal](10, 0) NULL,
	[TRADE_TERM] [nvarchar](3) NULL,
	[TRADETERM_DESCP] [nvarchar](30) NULL,
	[INCOTERM_CD] [nvarchar](3) NULL,
	[INCOTERM_DESCP] [nvarchar](30) NULL,
	[LOADING_FROM] [nvarchar](5) NULL,
	[LOADING_TO] [nvarchar](5) NULL,
	[PICKUP_CDATE] [date] NULL,
	[CARRIER] [nvarchar](20) NULL,
	[CARRIER_NM] [nvarchar](70) NULL,
	[SCAC_CD] [nvarchar](20) NULL,
	[FRT_TERM] [nvarchar](2) NULL,
	[CON_FREE_TIME] [int] NULL,
	[MASTER_NO] [nvarchar](20) NULL,
	[HOUSE_NO] [nvarchar](20) NULL,
	[SVC_CONTACT] [nvarchar](20) NULL,
	[WH_TIME] [datetime] NULL,
	[POR_CD] [nvarchar](5) NULL,
	[POR_CNTY] [nvarchar](2) NULL,
	[POR_NAME] [nvarchar](30) NULL,
	[IB_WINDOW] [nvarchar](200) NULL,
	[FACT_TIME] [datetime] NULL,
	[POL_CD] [nvarchar](5) NULL,
	[POL_CNTY] [nvarchar](2) NULL,
	[POL_NAME] [nvarchar](30) NULL,
	[PORT_ETA] [date] NULL,
	[EMPTY_TIME] [datetime] NULL,
	[POD_CD] [nvarchar](5) NULL,
	[POD_CNTY] [nvarchar](2) NULL,
	[POD_NAME] [nvarchar](30) NULL,
	[PORT_ATA] [datetime] NULL,
	[BACK_LOCATION] [nvarchar](50) NULL,
	[DEST_CD] [nvarchar](5) NULL,
	[DEST_CNTY] [nvarchar](2) NULL,
	[DEST_NAME] [nvarchar](30) NULL,
	[PORT_RLS_DATE] [datetime] NULL,
	[WM_CUT_DATE] [datetime] NULL,
	[VESSEL1] [nvarchar](30) NULL,
	[VOYAGE1] [nvarchar](12) NULL,
	[ETD1] [date] NULL,
	[ETA1] [date] NULL,
	[VESSEL2] [nvarchar](30) NULL,
	[VOYAGE2] [nvarchar](12) NULL,
	[ETD2] [date] NULL,
	[ETA2] [date] NULL,
	[VESSEL3] [nvarchar](30) NULL,
	[VOYAGE3] [nvarchar](12) NULL,
	[ETD3] [date] NULL,
	[ETA3] [date] NULL,
	[VESSEL4] [nvarchar](30) NULL,
	[VOYAGE4] [nvarchar](12) NULL,
	[ETD4] [date] NULL,
	[ETA4] [date] NULL,
	[ETD] [date] NULL,
	[ETA] [date] NULL,
	[ATP] [date] NULL,
	[ATD] [date] NULL,
	[ATA] [date] NULL,
	[OEXPORTER] [nvarchar](10) NULL,
	[OEXPORTER_NM] [nvarchar](70) NULL,
	[OEXPORTER_ADDR] [nvarchar](140) NULL,
	[OIMPORTER] [nvarchar](10) NULL,
	[OIMPORTER_NM] [nvarchar](70) NULL,
	[OIMPORTER_ADDR] [nvarchar](140) NULL,
	[IMPORT_NO] [nvarchar](50) NULL,
	[DEC_NO] [nvarchar](50) NULL,
	[CER_NO] [nvarchar](50) NULL,
	[DEC_DATE] [date] NULL,
	[REL_DATE] [date] NULL,
	[INSPECTION] [nvarchar](50) NULL,
	[DEC_CUST] [text] NULL,
	[DEC_REPLY] [text] NULL,
	[TC_IMPORTER] [nvarchar](10) NULL,
	[TC_IMPORTER_NM] [nvarchar](70) NULL,
	[TC_IMPORTER_ADDR] [nvarchar](140) NULL,
	[TC_IMPORT_NO] [nvarchar](50) NULL,
	[TC_DEC_NO] [nvarchar](50) NULL,
	[TC_CER_NO] [nvarchar](50) NULL,
	[TC_DEC_DATE] [date] NULL,
	[TC_REL_DATE] [date] NULL,
	[TC_INSPECTION] [nvarchar](50) NULL,
	[TC_DEC_CUST] [text] NULL,
	[TC_DEC_REPLY] [text] NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_BY] [nvarchar](40) NULL,
	[MODIFY_DATE] [datetime] NULL,
	[MODIFY_BY] [nvarchar](40) NULL,
	[AIRLINE_CD] [nvarchar](10) NULL,
	[AIRLINE_NM] [nvarchar](70) NULL,
	[QTY] [int] NULL,
	[QTYU] [nvarchar](10) NULL,
	[VW] [decimal](10, 3) NULL,
	[OF_COST] [decimal](10, 2) NULL,
	[TRUCK_COST] [decimal](10, 2) NULL,
	[CW] [decimal](10, 3) NULL,
	[HORN] [nvarchar](1) NULL,
	[BATTERY] [nvarchar](1) NULL,
	[TRUCK_CD] [nvarchar](20) NULL,
	[O_LOCATION] [nvarchar](10) NULL,
	[CSTATUS] [nvarchar](1) NULL,
	[BSTATUS] [nvarchar](1) NULL,
	[DN_NO] [nvarchar](100) NULL,
	[LOT_NO] [nvarchar](20) NULL,
	[BL_WIN] [nvarchar](40) NULL,
	[TERMINAL_CD] [nvarchar](30) NULL,
	[TERMINAL_NM] [nvarchar](70) NULL,
	[HS_CODE] [nvarchar](20) NULL,
	[HS_CODE_NO] [nvarchar](20) NULL,
	[TC_HS_CODE] [nvarchar](20) NULL,
	[TC_HS_CODE_NO] [nvarchar](20) NULL,
	[PRODUCT_TYPE] [nvarchar](20) NULL,
	[CONTAINER_YARD_CD] [nvarchar](20) NULL,
	[CONTAINER_YARD_NM] [nvarchar](300) NULL,
	[EXTRA_SRV] [nvarchar](50) NULL,
	[EXTRA_MEMO] [nvarchar](50) NULL,
	[FORK] [decimal](5, 0) NULL,
	[O_UID] [nvarchar](50) NULL,
	[CNTR_NO] [nvarchar](20) NULL,
	[CNTR_TYPE] [nvarchar](10) NULL,
	[DEC_INFO] [nvarchar](500) NULL,
	[O_ORDNO] [nvarchar](20) NULL,
	[ETA_MSL] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

 IF OBJECT_ID('dbo.SMRDN', 'U') IS NOT NULL 
 DROP TABLE dbo.SMRDN; 
CREATE TABLE [dbo].[SMRDN](
	[U_ID] [nvarchar](50) NULL,
	[GROUP_ID] [nvarchar](10) NULL,
	[CMP] [nvarchar](10) NULL,
	[STN] [nvarchar](10) NULL,
	[DEP] [nvarchar](10) NULL,
	[SHIPMENT_ID] [nvarchar](20) NULL,
	[DN_NO] [nvarchar](20) NULL,
	[INV_NO] [nvarchar](20) NULL,
	[NW] [numeric](10, 3) NULL,
	[GW] [numeric](10, 3) NULL,
	[GWU] [nvarchar](3) NULL,
	[CBM] [numeric](10, 3) NULL,
	[CBMU] [nvarchar](3) NULL,
	[QTY] [numeric](10, 3) NULL,
	[QTYU] [nvarchar](3) NULL,
	[PKG_NUM] [numeric](10, 0) NULL,
	[PKG_UNIT] [nvarchar](20) NULL,
	[PKG_UNIT_DESC] [nvarchar](100) NULL,
	[CNT20] [numeric](3, 0) NULL,
	[CNT40] [numeric](3, 0) NULL,
	[CNT40HQ] [numeric](3, 0) NULL,
	[OTH_CNT_TYPE] [nvarchar](20) NULL,
	[OTH_CNT_NUM] [numeric](3, 0) NULL,
	[IMPORT_NO] [nvarchar](50) NULL,
	[DEC_NO] [nvarchar](50) NULL,
	[CER_NO] [nvarchar](50) NULL,
	[DEC_DATE] [datetime] NULL,
	[REL_DATE] [datetime] NULL,
	[INSPECTION] [nvarchar](1) NULL,
	[DEC_CUST] [text] NULL,
	[DEC_REPLY] [text] NULL,
	[TC_IMPORT_NO] [nvarchar](50) NULL,
	[TC_DEC_NO] [nvarchar](50) NULL,
	[TC_CER_NO] [nvarchar](50) NULL,
	[TC_DEC_DATE] [datetime] NULL,
	[TC_REL_DATE] [datetime] NULL,
	[TC_INSPECTION] [nvarchar](50) NULL,
	[TC_DEC_CUST] [text] NULL,
	[TC_DEC_REPLY] [text] NULL,
	[DLV_AREA] [nvarchar](20) NULL,
	[DLV_AREA_NM] [nvarchar](70) NULL,
	[ADDR_CODE] [nvarchar](10) NULL,
	[DLV_ADDR] [nvarchar](350) NULL,
	[RESERVE_NO] [nvarchar](20) NULL,
	[WS_CD] [nvarchar](10) NULL,
	[PICKUP_DATE] [datetime] NULL,
	[ARRIVAL_DATE] [datetime] NULL,
	[ORD_NO] [nvarchar](20) NULL,
	[LOT_NO] [nvarchar](20) NULL,
	[ADD_POINT] [nvarchar](1) NULL,
	[PICK_AREA] [nvarchar](20) NULL,
	[PICK_AREA_NM] [nvarchar](70) NULL,
	[CANCEL_NO] [nvarchar](20) NULL,
	[IDATE] [datetime] NULL,
	[LDATE] [datetime] NULL,
	[POD_MDATE] [datetime] NULL,
	[SEAL_CHECK] [nvarchar](1) NULL,
	[FLOOR_CHECK] [nvarchar](1) NULL,
	[POD_CHECK] [nvarchar](1) NULL,
	[EXPP_CHECK] [nvarchar](1) NULL,
	[DISCHARGE_DATE] [date] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

IF OBJECT_ID('dbo.SMRCNTR', 'U') IS NOT NULL 
 DROP TABLE dbo.SMRCNTR; 
CREATE TABLE [dbo].[SMRCNTR](
	[U_ID] [nvarchar](50) NOT NULL,
	[SHIPMENT_ID] [nvarchar](20) NOT NULL,
	[CMP] [nvarchar](10) NULL,
	[CNTR_NO] [nvarchar](20) NULL,
	[CNTR_TYPE] [nvarchar](10) NULL,
	[SEAL_NO1] [nvarchar](20) NULL,
	[SEAL_NO2] [nvarchar](20) NULL,
	[DN_NO] [nvarchar](500) NULL,
	[DIVISION_DESCP] [nvarchar](500) NULL,
	[QTY] [int] NULL,
	[QTYU] [nvarchar](3) NULL,
	[GW] [numeric](10, 3) NULL,
	[GWU] [nvarchar](3) NULL,
	[CBM] [numeric](10, 4) NULL,
	[IMPORT_NO] [nvarchar](50) NULL,
	[DEC_NO] [nvarchar](50) NULL,
	[CER_NO] [nvarchar](50) NULL,
	[DEC_DATE] [datetime] NULL,
	[REL_DATE] [datetime] NULL,
	[INSPECTION] [nvarchar](1) NULL,
	[DEC_CUST] [text] NULL,
	[DEC_REPLY] [text] NULL,
	[TC_IMPORT_NO] [nvarchar](50) NULL,
	[TC_DEC_NO] [nvarchar](50) NULL,
	[TC_CER_NO] [nvarchar](50) NULL,
	[TC_DEC_DATE] [datetime] NULL,
	[TC_REL_DATE] [datetime] NULL,
	[TC_INSPECTION] [nvarchar](1) NULL,
	[TC_DEC_CUST] [text] NULL,
	[TC_DEC_REPLY] [text] NULL,
	[RESERVE_NO] [nvarchar](20) NULL,
	[DLV_AREA] [nvarchar](20) NULL,
	[DLV_AREA_NM] [nvarchar](70) NULL,
	[ADDR_CODE] [nvarchar](10) NULL,
	[DLV_ADDR] [nvarchar](350) NULL,
	[ORD_NO] [nvarchar](20) NOT NULL,
	[PICKUP_DATE] [datetime] NULL,
	[ARRIVAL_DATE] [datetime] NULL,
	[WS_CD] [nvarchar](10) NULL,
	[LOT_NO] [nvarchar](20) NULL,
	[PICK_AREA] [nvarchar](20) NULL,
	[PICK_AREA_NM] [nvarchar](70) NULL,
	[CANCEL_NO] [nvarchar](20) NULL,
	[GROUP_ID] [nvarchar](10) NULL,
	[STN] [nvarchar](10) NULL,
	[DEP] [nvarchar](10) NULL,
	[IDATE] [datetime] NULL,
	[LDATE] [datetime] NULL,
	[POD_MDATE] [datetime] NULL,
	[SEAL_CHECK] [nvarchar](1) NULL,
	[FLOOR_CHECK] [nvarchar](1) NULL,
	[POD_CHECK] [nvarchar](1) NULL,
	[EXPP_CHECK] [nvarchar](1) NULL,
	[DISCHARGE_DATE] [date] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]


IF OBJECT_ID('dbo.TMP_AMT', 'U') IS NOT NULL 
 DROP TABLE dbo.TMP_AMT; 
CREATE TABLE [dbo].[TMP_AMT](
	[SHIPMENT_ID] [nvarchar](20) NULL,
	[LOT_NO] [nvarchar](20) NULL,
	[CHG_CD] [nvarchar](10) NULL,
	[QCUR] [nvarchar](3) NULL,
	[QAMT] [numeric](18, 3) NULL,
	[RESERVE_NO] [nvarchar](20) NULL,
	[CNTR_NO] [nvarchar](20) NULL
) ON [PRIMARY]


IF OBJECT_ID('dbo.SMQTI', 'U') IS NOT NULL 
 DROP TABLE dbo.SMQTI; 
CREATE TABLE [dbo].[SMQTI](
	[U_ID] [nvarchar](50) NOT NULL,
	[GROUP_ID] [nvarchar](10) NULL,
	[CMP] [nvarchar](10) NULL,
	[STN] [nvarchar](10) NULL,
	[DEP] [nvarchar](10) NULL,
	[CHG_CD] [nvarchar](10) NULL,
	[POD_CD] [nvarchar](20) NULL,
	[I_TYPE] [nvarchar](20) NULL,
	[CARRIER_CD] [nvarchar](20) NULL,
	[CARRIER_NM] [nvarchar](70) NULL,
	[CNT_TYPE] [nvarchar](10) NULL,
	[S_DAY] [int] NULL,
	[E_DAY] [int] NULL,
	[FEE_PER_DAY] [numeric](18, 2) NULL,
	[CUR] [nvarchar](3) NULL,
	[EMPTY_RETURN] [nvarchar](20) NULL,
	[TERMINAL_CD] [nvarchar](20) NULL,
	[CAL_TYPE] [nvarchar](1) NULL,
	[PERCENTAGE] [numeric](5, 2) NULL,
	[FOB_CIF] [nvarchar](1) NULL,
	[Order_Seq] [int] NULL,
 CONSTRAINT [PK_SMQTI] PRIMARY KEY CLUSTERED 
(
	[U_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


ALTER TABLE SMRV ADD ARRIVAL_DATE DATETIME
ALTER TABLE SMRV ADD TRAIN_FLIGHT NVARCHAR(100)
ALTER TABLE SMRV ADD ORD_NO NVARCHAR(20)
ALTER TABLE SMRV ADD CALL_TYPE NVARCHAR(1)
ALTER TABLE SMRV ADD ORD_INFO NVARCHAR(500)

ALTER TABLE SMRV ADD TRUCK_RMK NVARCHAR(500)
ALTER TABLE SMRV ADD WS_RMK NVARCHAR(500)
ALTER TABLE SMAL ADD DLV_AREA  NVARCHAR(20)
ALTER TABLE SMAL ADD DLV_AREA_NM  NVARCHAR(70)
ALTER TABLE SMAL ADD ADDR_CODE  NVARCHAR(10)
ALTER TABLE SMAL ADD DLV_ADDR NVARCHAR(350)

ALTER TABLE SMIDN ADD SCMREQUEST_DATE DATETIME
ALTER TABLE SMICNTR ADD SCMREQUEST_DATE DATETIME
ALTER TABLE SMIDN ADD PRIORITY INT
ALTER TABLE SMICNTR ADD PRIORITY INT
ALTER TABLE SMSMI ADD INBOUND_PO_NO nvarchar(30)
ALTER TABLE SMSMI ADD TC_IMPORTER_REMARK nvarchar(2000)
ALTER TABLE SMSMI ADD CC_IMPORTER_REMARK nvarchar(2000)


IF OBJECT_ID('dbo.SMICUFT', 'U') IS NOT NULL 
 DROP TABLE dbo.SMICUFT; 
CREATE TABLE [dbo].[SMICUFT](
	[U_ID] [nvarchar](50) NOT NULL,
	[U_FID] [nvarchar](50) NOT NULL,
	[DN_NO] [nvarchar](20) NULL,
	[L] [numeric](10, 2) NULL,
	[W] [numeric](10, 2) NULL,
	[H] [numeric](10, 2) NULL,
	[PKG] [numeric](10, 2) NULL,
	[PKG_UNIT] [nvarchar](10) NULL,
	[CUFT] [numeric](16, 4) NULL,
	[VW] [numeric](16, 4) NULL
) ON [PRIMARY]

IF OBJECT_ID('dbo.SMSMIPT', 'U') IS NOT NULL 
 DROP TABLE dbo.SMSMIPT; 
 CREATE TABLE [dbo].[SMSMIPT](
	[U_ID] [nvarchar](50) NOT NULL,
	[U_FID] [nvarchar](50) NULL,
	[SHIPMENT_ID] [nvarchar](20) NULL,
	[PARTY_TYPE] [nvarchar](10) NULL,
	[TYPE_DESCP] [nvarchar](30) NULL,
	[ORDER_BY] [nvarchar](3) NULL,
	[PARTY_NO] [nvarchar](10) NULL,
	[PARTY_NAME] [nvarchar](70) NULL,
	[PARTY_NAME2] [nvarchar](70) NULL,
	[PARTY_NAME3] [nvarchar](70) NULL,
	[PARTY_NAME4] [nvarchar](70) NULL,
	[PARTY_ADDR1] [nvarchar](60) NULL,
	[PARTY_ADDR2] [nvarchar](40) NULL,
	[PARTY_ADDR3] [nvarchar](40) NULL,
	[PARTY_ADDR4] [nvarchar](40) NULL,
	[PARTY_ADDR5] [nvarchar](40) NULL,
	[CNTY] [nvarchar](2) NULL,
	[CNTY_NM] [nvarchar](30) NULL,
	[CITY] [nvarchar](3) NULL,
	[CITY_NM] [nvarchar](30) NULL,
	[STATE] [nvarchar](2) NULL,
	[ZIP] [nvarchar](10) NULL,
	[PARTY_ATTN] [nvarchar](80) NULL,
	[PARTY_TEL] [nvarchar](50) NULL,
	[PARTY_MAIL] [nvarchar](100) NULL,
	[DEBIT_TO] [nvarchar](10) NULL,
	[FAX_NO] [nvarchar](30) NULL,
	[TAX_NO] [nvarchar](20) NULL,
 CONSTRAINT [PK_SMSMIPT] PRIMARY KEY CLUSTERED 
(
	[U_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

 IF OBJECT_ID('dbo.SMAL', 'U') IS NOT NULL 
 DROP TABLE dbo.SMAL; 
 CREATE TABLE [dbo].[SMAL](
	[U_ID] [nvarchar](50) NOT NULL,
	[GROUP_ID] [nvarchar](10) NULL,
	[CMP] [nvarchar](10) NULL,
	[STN] [nvarchar](10) NULL,
	[DEP] [nvarchar](10) NULL,
	[TRAN_TYPE] [nvarchar](1) NULL,
	[FREIGHT_TERM] [nvarchar](2) NULL,
	[TRANSACTE_MODE] [nvarchar](2) NULL,
	[INCOTERM_CD] [nvarchar](3) NULL,
	[CONN_CD] [nvarchar](30) NULL,
	[CONN_NM] [nvarchar](70) NULL,
	[POD_CD] [nvarchar](5) NULL,
	[POD_NM] [nvarchar](30) NULL,
	[PARTY_TYPE] [nvarchar](300) NULL,
	[LSP_CD] [nvarchar](30) NULL,
	[LSP_NM] [nvarchar](70) NULL,
	[REMARK] [nvarchar](500) NULL,
	[CREATE_BY] [nvarchar](40) NULL,
	[CREATE_DATE] [datetime] NULL,
	[MODIFY_BY] [nvarchar](40) NULL,
	[MODIFY_DATE] [datetime] NULL,
	[TERMINAL_CD] [nvarchar](30) NULL,
	[TERMINAL_NM] [nvarchar](70) NULL,
	[DLV_AREA] [nvarchar](20) NULL,
	[DLV_AREA_NM] [nvarchar](70) NULL,
	[ADDR_CODE] [nvarchar](10) NULL,
	[DLV_ADDR] [nvarchar](350) NULL,
 CONSTRAINT [PK_SMAL] PRIMARY KEY CLUSTERED 
(
	[U_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

  IF OBJECT_ID('dbo.BSLIGHTM', 'U') IS NOT NULL 
 DROP TABLE dbo.BSLIGHTM; 
 CREATE TABLE [dbo].[BSLIGHTM](
	[U_ID] [nvarchar](50) NOT NULL,
	[GROUP_ID] [nvarchar](10) NULL,
	[CMP] [nvarchar](10) NULL,
	[STN] [nvarchar](10) NULL,
	[DEP] [nvarchar](10) NULL,
	[CUST_CD] [nvarchar](30) NULL,
	[CUST_NM] [nvarchar](70) NULL,
	[CREATE_BY] [nvarchar](40) NULL,
	[CREATE_DATE] [datetime] NULL,
	[MODIFY_BY] [nvarchar](40) NULL,
	[MODIFY_DATE] [datetime] NULL,
 CONSTRAINT [PK_BSLIGHTM] PRIMARY KEY CLUSTERED 
(
	[U_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

  IF OBJECT_ID('dbo.BSLIGHTD', 'U') IS NOT NULL 
 DROP TABLE dbo.BSLIGHTD; 
 CREATE TABLE [dbo].[BSLIGHTD](
	[U_ID] [nvarchar](50) NOT NULL,
	[U_FID] [nvarchar](50) NOT NULL,
	[CUST_CD] [nvarchar](30) NOT NULL,
	[IO] [nvarchar](1) NULL,
	[TRAN_TYPE] [nvarchar](1) NULL,
	[L1] [nvarchar](20) NULL,
	[L2] [nvarchar](20) NULL,
	[L3] [nvarchar](20) NULL,
	[L4] [nvarchar](20) NULL,
	[L5] [nvarchar](20) NULL,
	[L6] [nvarchar](20) NULL,
	[L7] [nvarchar](20) NULL,
	[L8] [nvarchar](20) NULL,
	[L9] [nvarchar](20) NULL,
	[L10] [nvarchar](20) NULL,
 CONSTRAINT [PK_BSLIGHTD_1] PRIMARY KEY CLUSTERED 
(
	[U_ID] ASC,
	[U_FID] ASC,
	[CUST_CD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

  IF OBJECT_ID('dbo.SMWH', 'U') IS NOT NULL 
 DROP TABLE dbo.SMWH; 
 CREATE TABLE [dbo].[SMWH](
	[GROUP_ID] [nvarchar](10) NOT NULL,
	[CMP] [nvarchar](10) NOT NULL,
	[WS_CD] [nvarchar](10) NOT NULL,
	[WS_NM] [nvarchar](30) NOT NULL,
	[GATE_NUMBER] [numeric](3, 0) NULL,
	[PRODUCT_LINE] [nvarchar](40) NULL,
	[REF_GATE] [nvarchar](50) NULL,
	[PIC] [nvarchar](20) NULL,
	[REMARK] [nvarchar](50) NULL,
	[MODIFY_BY] [nvarchar](40) NULL,
	[MODIFY_DATE] [date] NULL,
	[CREATE_BY] [nvarchar](40) NULL,
	[CREATE_DATE] [datetime] NULL,
	[U_ID] [nvarchar](50) NULL,
	[MF_NO] [nvarchar](5) NULL,
	[DLV_AREA] [nvarchar](20) NULL,
	[DLV_AREA_NM] [nvarchar](70) NULL,
	[DLV_ADDR] [nvarchar](10) NULL,
	[DLV_ADDR_NM] [nvarchar](200) NULL
) ON [PRIMARY]

IF OBJECT_ID('dbo.SMWHGT', 'U') IS NOT NULL 
DROP TABLE dbo.SMWHGT; 
 CREATE TABLE [dbo].[SMWHGT](
	[CMP] [nvarchar](10) NOT NULL,
	[WS_CD] [nvarchar](10) NOT NULL,
	[GATE_NO] [nvarchar](5) NULL,
	[LIFT] [nvarchar](1) NULL,
	[STATUS] [nvarchar](1) NULL,
	[CNTR_NO] [nvarchar](20) NULL,
	[REMARK] [nvarchar](50) NULL,
	[SUSPEND_FROM] [datetime] NULL,
	[SUSPEND_TO] [datetime] NULL,
	[RESERVE_NO] [nvarchar](20) NULL,
	[U_ID] [nvarchar](50) NULL,
	[U_FID] [nvarchar](50) NULL,
	[SEQ_NO] [int] NULL
) ON [PRIMARY]


IF OBJECT_ID('dbo.ECREFFEE', 'U') IS NOT NULL 
DROP TABLE dbo.ECREFFEE; 
CREATE TABLE [dbo].[ECREFFEE](
	[U_ID] [nvarchar](50) NOT NULL,
	[GROUP_ID] [nvarchar](10) NULL,
	[CMP] [nvarchar](10) NULL,
	[STN] [nvarchar](10) NULL,
	[DEP] [nvarchar](10) NULL,
	[CHG_CD] [nvarchar](10) NULL,
	[CHG_DESCP] [nvarchar](50) NULL,
	[CREATE_BY] [nvarchar](40) NULL,
	[CREATE_DATE] [datetime] NULL,
	[MODIFY_BY] [nvarchar](40) NULL,
	[MODIFY_DATE] [datetime] NULL,
	[CHG_ID] [nvarchar](20) NULL,
	[REMARK] [nvarchar](100) NULL,
	[SEQ_NO] [int] NULL,
	[GW] [numeric](10, 3) NULL,
	[CBM] [numeric](10, 3) NULL,
	[FEE_FROM] [numeric](10, 3) NULL,
	[FEE_TO] [numeric](10, 3) NULL,
	[VENDER_CD] [nvarchar](30) NULL,
	[VENDER_NM] [nvarchar](70) NULL,
	[FEE_TYPE] [nvarchar](1) NULL,
	[FEE_WEIGHT] [numeric](10, 3) NULL,
	[FEE_OP] [nvarchar](1) NULL,
	[CAL_TYPE] [nvarchar](1) NULL,
	[PUNIT] [nvarchar](10) NULL
) ON [PRIMARY]

ALTER TABLE SMRV
ALTER COLUMN CREATE_BY NVARCHAR(40)
ALTER TABLE SMRV
ALTER COLUMN ORDER_BY NVARCHAR(40)
ALTER TABLE SMRV
ALTER COLUMN CONFIRM_BY NVARCHAR(40)
ALTER TABLE SMRV
ALTER COLUMN IN_BY NVARCHAR(40)
ALTER TABLE SMRV
ALTER COLUMN SEAL_BY NVARCHAR(40)
ALTER TABLE SMRV
ALTER COLUMN SMCREATE_BY NVARCHAR(40)

ALTER TABLE SMRV ALTER COLUMN WS_CD NVARCHAR(40)
ALTER TABLE SMSMI ADD INVOICE_INFO NVARCHAR(500);
ALTER TABLE SMSMI ADD PRODUCT_INFO NVARCHAR(500);
ALTER TABLE SMRCNTR ADD EMPTY_TIME DATETIME;

ALTER TABLE SMORD ADD ARRIVAL_DATE DATETIME;
ALTER TABLE SMRV ADD PRIORITY INT;
ALTER TABLE SMSMI ADD EXRERNAL_INFO NVARCHAR(200);

ALTER TABLE SMRV ADD PRODUCT_TYPE_INFO NVARCHAR(300);
ALTER TABLE SMBID ADD CNTR_INFO NVARCHAR(500);
ALTER TABLE SMBID ADD MASTER_NO NVARCHAR(20);
ALTER TABLE SMBID ADD POD_CD NVARCHAR(5);
ALTER TABLE SMICNTR ALTER COLUMN SCMREQUEST_DATE DATE
ALTER TABLE SMIDN ALTER COLUMN SCMREQUEST_DATE DATE
ALTER TABLE SMSMI ALTER COLUMN PRODUCTION_DATE DATE
ALTER TABLE SMRV ALTER COLUMN CNTR_NO NVARCHAR(200);

IF OBJECT_ID('dbo.BSTERM', 'U') IS NOT NULL 
 DROP TABLE dbo.BSTERM; 
CREATE TABLE [dbo].[BSTERM](
	[U_ID] [nvarchar](40) NULL,
	[GROUP_ID] [nvarchar](10) NULL,
	[CMP] [nvarchar](10) NULL,
	[IO_FLAG] [nvarchar](1) NULL,
	[FRT_TERM] [nvarchar](2) NULL,
	[INCOTERM_CD] [nvarchar](3) NULL,
	[INCOTERM_DESCP] [nvarchar](30) NULL,
	[POD_CD] [nvarchar](5) NULL,
	[POD_NAME] [nvarchar](30) NULL,
	[NEED_CHG][nvarchar](20)NULL,
	[CREATE_DATE] [datetime] NULL,
	[CREATE_BY] [nvarchar](40) NULL,
	[MODIFY_DATE] [datetime] NULL,
	[MODIFY_BY] [nvarchar](40) NULL
) ON [PRIMARY]

ALTER TABLE SMSMI ADD TRAN_REMARK NVARCHAR(500)
ALTER TABLE SMSMI ADD CC_REMARK NVARCHAR(500)
ALTER TABLE SMSMI ADD BOOKING_WIN NVARCHAR(40)
ALTER TABLE SMSMI ADD SALSE_WIN NVARCHAR(40)
ALTER TABLE SMRV ADD WS_NM NVARCHAR(50);
ALTER TABLE SMORD ADD ETA_MSL_TIME NUMERIC(2,0);
ALTER TABLE SMORD ALTER COLUMN ETA_MSL DATE
ALTER TABLE SMAL ADD INCOTERM_DESCP NVARCHAR(30);
ALTER TABLE SMSMI ADD IS_DIRECTLYNB NVARCHAR(1);
ALTER TABLE SMORD ADD IS_DIRECTLYNB NVARCHAR(1);
ALTER TABLE SMRV ADD IS_DIRECTLYNB NVARCHAR(1);
ALTER TABLE SMQTD ADD CARRIER_CODE NVARCHAR(20);
ALTER TABLE SMQTD ADD CARRIER_NAME NVARCHAR(300);