//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace Business.TPV.LspWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TPVServiceSoap", Namespace="http://penavicoxm.com/LogisticWebServices/")]
    public partial class TPVService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private TpvSoapHeader tpvSoapHeaderValueField;
        
        private System.Threading.SendOrPostCallback TPVDataExchangeOperationCompleted;
        
        private System.Threading.SendOrPostCallback TPVBrokerExchangeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TPVService() {
            this.Url = global::Business.TPV.Properties.Settings.Default.Business_TPV_LspWS_TPVService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public TpvSoapHeader TpvSoapHeaderValue {
            get {
                return this.tpvSoapHeaderValueField;
            }
            set {
                this.tpvSoapHeaderValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TPVDataExchangeCompletedEventHandler TPVDataExchangeCompleted;
        
        /// <remarks/>
        public event TPVBrokerExchangeCompletedEventHandler TPVBrokerExchangeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TpvSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://penavicoxm.com/LogisticWebServices/TPVDataExchange", RequestNamespace="http://penavicoxm.com/LogisticWebServices/", ResponseNamespace="http://penavicoxm.com/LogisticWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultInfo TPVDataExchange(string className, string datas) {
            object[] results = this.Invoke("TPVDataExchange", new object[] {
                        className,
                        datas});
            return ((ResultInfo)(results[0]));
        }
        
        /// <remarks/>
        public void TPVDataExchangeAsync(string className, string datas) {
            this.TPVDataExchangeAsync(className, datas, null);
        }
        
        /// <remarks/>
        public void TPVDataExchangeAsync(string className, string datas, object userState) {
            if ((this.TPVDataExchangeOperationCompleted == null)) {
                this.TPVDataExchangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTPVDataExchangeOperationCompleted);
            }
            this.InvokeAsync("TPVDataExchange", new object[] {
                        className,
                        datas}, this.TPVDataExchangeOperationCompleted, userState);
        }
        
        private void OnTPVDataExchangeOperationCompleted(object arg) {
            if ((this.TPVDataExchangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TPVDataExchangeCompleted(this, new TPVDataExchangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("TpvSoapHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://penavicoxm.com/LogisticWebServices/TPVBrokerExchange", RequestNamespace="http://penavicoxm.com/LogisticWebServices/", ResponseNamespace="http://penavicoxm.com/LogisticWebServices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultInfo TPVBrokerExchange(string className, string datas) {
            object[] results = this.Invoke("TPVBrokerExchange", new object[] {
                        className,
                        datas});
            return ((ResultInfo)(results[0]));
        }
        
        /// <remarks/>
        public void TPVBrokerExchangeAsync(string className, string datas) {
            this.TPVBrokerExchangeAsync(className, datas, null);
        }
        
        /// <remarks/>
        public void TPVBrokerExchangeAsync(string className, string datas, object userState) {
            if ((this.TPVBrokerExchangeOperationCompleted == null)) {
                this.TPVBrokerExchangeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTPVBrokerExchangeOperationCompleted);
            }
            this.InvokeAsync("TPVBrokerExchange", new object[] {
                        className,
                        datas}, this.TPVBrokerExchangeOperationCompleted, userState);
        }
        
        private void OnTPVBrokerExchangeOperationCompleted(object arg) {
            if ((this.TPVBrokerExchangeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TPVBrokerExchangeCompleted(this, new TPVBrokerExchangeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://penavicoxm.com/LogisticWebServices/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://penavicoxm.com/LogisticWebServices/", IsNullable=false)]
    public partial class TpvSoapHeader : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://penavicoxm.com/LogisticWebServices/")]
    public partial class ResultInfo {
        
        private ResultCodeInfo resultCodeField;
        
        private string resultDescField;
        
        private string resultDataField;
        
        /// <remarks/>
        public ResultCodeInfo ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ResultDesc {
            get {
                return this.resultDescField;
            }
            set {
                this.resultDescField = value;
            }
        }
        
        /// <remarks/>
        public string ResultData {
            get {
                return this.resultDataField;
            }
            set {
                this.resultDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1067.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://penavicoxm.com/LogisticWebServices/")]
    public enum ResultCodeInfo {
        
        /// <remarks/>
        UserPasswordError,
        
        /// <remarks/>
        Succeed,
        
        /// <remarks/>
        XmlValidateError,
        
        /// <remarks/>
        DataError,
        
        /// <remarks/>
        SystemError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TPVDataExchangeCompletedEventHandler(object sender, TPVDataExchangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TPVDataExchangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TPVDataExchangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    public delegate void TPVBrokerExchangeCompletedEventHandler(object sender, TPVBrokerExchangeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TPVBrokerExchangeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TPVBrokerExchangeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591